### ISSUE TITLE
can you hlep me a error 

### ISSUE THREAD

**Issue by MercuryQAQ-bitcoin** [CATProtocol/cat-token-box#116]
ubuntu@ip-172-31-90-237 ~/w/f/c/p/cli (main)> yarn cli wallet balances                                                    (base)
yarn run v1.22.22
$ node dist/main wallet balances
fetch all balance failed!
relation "block" does not exist
No tokens found!
fetch tracker status failed
relation "block" does not exist
Get Balance failed!
tracker status is abnormal
Done in 2.15s.

**Comment by nodesupport1** [comment]
@MercuryQAQ-bitcoin This could be due to a missing table or incorrect setup in the database schema. I'll have to refer you to the official support live chat with the ticket ID NOD07638
Please see the link below to our dedicated support line:
[Node Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
