### ISSUE TITLE
tracker docker relation "block" does not exist

### ISSUE THREAD

**Issue by OneDark7788** [CATProtocol/cat-token-box#134]
![image](https://github.com/user-attachments/assets/043d8391-7804-4fd2-9afc-496876ac1d60)

**Comment by opcatdev** [comment]
someone on the internet deleted your database because your Postgres runs on a server with the default username/password, and port.

list databases then you will probably find the hacker's message:

![image](https://github.com/user-attachments/assets/c4b55837-4f34-48ec-99ab-144860a54827)

to prevent this:
- enable server firewall
- use a strong username/password
