### ISSUE TITLE
unable connect to database

### ISSUE THREAD

**Issue by minhduytran** [CATProtocol/cat-token-box#26]
when i run sudo yarn cli wallet balances, it return error
![image](https://github.com/user-attachments/assets/f14d8f5f-9d13-406f-a6ec-d5d00fc1fdd5)

**Comment by orchidtexture** [comment]
what DATABASE_HOST are you assigning at packages/tracker/.env?

**Comment by minhduytran** [comment]
Hi @orchidtexture ,

i use default setting
![image](https://github.com/user-attachments/assets/b7145f16-389b-4c38-9c37-40481860532f)

**Comment by orchidtexture** [comment]
After you have the postgres and fractal node running, instead of running the tracker with docker, try this: 
cd into the tracker directory. cat/packages/tracker
`yarn install`
`yarn build`
IF YOU CHANGE THE CODE AT ALL YOU WILL NEED TO RUN YARN BUILD AGAIN TO APPLY CHANGES
`yarn run start:prod`

It should start syncing

**Comment by anonymous-sushi** [comment]
postgres container is trash

**Comment by minhduytran** [comment]
hi @orchidtexture 
I fixed this issue. The problem came from my VPS blocking port 5432. I unlocked it, and the process ran smoothly.
